name: 'qiandao'

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 17 * * *'

jobs:
  csdn-emailbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # - name: 'Install dependencies'
      #   run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -r ./requirement.txt
      - name: 'Working'
        run: python qiandao.py
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: 市场收益
          body: 签到成功
          to: 568654196@qq.com
          from: GitHub Actions
          content_type: text/plain
